hubmapconsortium/hra-ui

libs/state/src/lib/cell-summary/cell-summary.selectors.spec.ts
libs/state/src/lib/cell-summary/cell-summary.selectors.ts
libs/state/src/lib/cell-summary/cell-summary.spec.ts

This PR adds selectors for the `CellSummary` State

Cell summary selectors1

---

libs/components/organisms/src/lib/biomarker-table/biomarker-table.component.scss

Clean up overlapping borders #175

---

apps/ftu-ui/src/assets/links.yml
apps/ftu-ui/src/assets/resources.yml

Fix routing

---

apps/ftu-ui-small-wc/src/app/app.component.ts
apps/ftu-ui/src/app/app.component.ts
libs/components/molecules/src/lib/footer/footer.component.html
libs/components/molecules/src/lib/footer/footer.component.scss
libs/components/molecules/src/lib/tissue-tree-list/tissue-tree-list.component.scss

* tree-height
* optional value

Design Changes (#261)

---

apps/ftu-ui-small-wc/src/index.html
libs/components/behavioral/src/lib/biomarker-details/biomarker-details.component.scss
libs/components/molecules/src/lib/fullscreen/fullscreen-content.component.scss

* table styles fix
* fixes animation in mozillla
---------

table styles fix (#264)

---

libs/components/behavioral/src/lib/tissue-library-behavior/tissue-library-behavior.component.html
libs/components/behavioral/src/lib/tissue-library-behavior/tissue-library-behavior.component.ts
libs/components/molecules/src/lib/tissue-tree-list/tissue-tree-list.component.html
libs/components/molecules/src/lib/tissue-tree-list/tissue-tree-list.component.spec.ts
libs/components/molecules/src/lib/tissue-tree-list/tissue-tree-list.component.ts

adds navigation using up/down arrows

---

libs/components/behavioral/src/lib/biomarker-details/biomarker-details.component.html
libs/components/behavioral/src/lib/biomarker-details/biomarker-details.component.ts
libs/components/behavioral/src/lib/medical-illustration-behavior/medical-illustration-behavior.component.html
libs/components/behavioral/src/lib/medical-illustration-behavior/medical-illustration-behavior.component.ts
libs/components/molecules/src/lib/interactive-svg/interactive-svg.component.ts
libs/components/organisms/src/lib/biomarker-table/biomarker-table.component.html
libs/components/organisms/src/lib/biomarker-table/biomarker-table.component.scss
libs/components/organisms/src/lib/biomarker-table/biomarker-table.component.spec.ts
libs/components/organisms/src/lib/biomarker-table/biomarker-table.component.ts
libs/services/src/lib/ftu-data/ftu-data.impl.ts
libs/state/src/lib/illustrator/illustrator.actions.ts
libs/state/src/lib/illustrator/illustrator.selectors.ts
libs/state/src/lib/illustrator/illustrator.state.ts

Highlight corresponding cells in illustration when hovering over biomarker table entry

---

apps/ftu-ui/src/app/app.module.ts
libs/components/behavioral/src/lib/biomarker-details-wc/biomarker-details-wc.component.html
libs/components/behavioral/src/lib/biomarker-details-wc/biomarker-details-wc.component.spec.ts
libs/components/behavioral/src/lib/biomarker-details-wc/biomarker-details-wc.component.ts
libs/components/behavioral/src/lib/biomarker-details/biomarker-details.component.html
libs/components/behavioral/src/lib/biomarker-details/biomarker-details.component.spec.ts
libs/components/behavioral/src/lib/biomarker-details/biomarker-details.component.ts
libs/components/behavioral/src/lib/contact-behavior/contact-behavior.component.ts
libs/components/behavioral/src/lib/footer-behavior/footer-behavior.component.ts
libs/components/behavioral/src/lib/medical-illustration-behavior/medical-illustration-behavior.component.spec.ts
libs/components/molecules/src/lib/header/header.component.html
libs/components/molecules/src/lib/header/header.component.ts
libs/components/molecules/src/lib/source-list/source-list.component.html
libs/components/molecules/src/lib/source-list/source-list.component.ts
libs/state/src/lib/state-analytics-plugin/index.ts
libs/state/src/lib/state-analytics-plugin/mouse-tracker-module.ts
libs/state/src/lib/state-analytics-plugin/state-analytics-plugin.service.ts

Add google analytics tracking actions

---

apps/ccf-rui/src/app/app-web-component.component.ts
apps/ccf-rui/src/app/core/store/reference-data/reference-data.state.ts
apps/ccf-rui/src/environments/environment.ts

Added an option to the RUI to set the reference data url as it will become external in HRA v2.1

Externalize RUI reference data

---

apps/ccf-eui/src/app/core/store/data/data.state.ts
apps/ccf-rui/src/app/core/store/model/model.state.ts

Removed distinct check from viewType

---

apps/ccf-eui/src/app/app.component.ts
apps/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.html
apps/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.spec.ts
apps/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.ts
apps/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.module.ts

Improved the ontology tree by removing unused functionality that was slowing down performance.

Improved ontology tree performance

---

apps/cde-ui/src/app/pages/landing-page/landing-page.component.html
apps/cde-ui/src/app/pages/landing-page/landing-page.component.scss
apps/cde-ui/src/app/pages/landing-page/landing-page.component.theme.scss
apps/cde-ui/src/styles.scss
apps/cde-ui/src/styles/_cta.scss

- Fixed button states on the landing page
- fix vccf and cards section behavior on screen size > 1920px

fix button states and widescreen behavior

---

libs/cde-visualization/src/lib/components/cell-types/cell-types.component.ts

fix issue #415 . Added change detection on color change

fix color selection change detection

---

apps/humanatlas.io/src/app/shared/navigation-items.ts
apps/humanatlas.io/src/assets/content/pages/organ-gallery-in-vr.yaml
apps/humanatlas.io/src/assets/content/pages/overview-tools.yaml
apps/humanatlas.io/src/assets/content/pages/release-notes/v1.3.yaml

- renamed all instances of Organ Gallery in VR to HRA Organ Gallery
- added button for using the VR gallery
- removed the video section
- added a new reference

update hra organ gallery page

---

README.md
apps/cde-ui/src/main.ts
apps/cde-ui/src/styles/global/_fonts.scss
apps/dashboard-ui/src/styles/global/_fonts.scss

Fixed font weight issues in CDE and HRA-dashboard
https://github.com/hubmapconsortium/hra-ui/issues/439
https://github.com/hubmapconsortium/hra-ui/issues/470
https://github.com/hubmapconsortium/hra-ui/issues/472

Font fixes

---

libs/cde-visualization/src/lib/components/color-picker-label/color-picker-label.component.html
libs/cde-visualization/src/lib/components/color-picker-label/color-picker-label.component.ts
libs/design-system/footer/src/lib/footer.component.scss

Cde visualization label update

---

apps/ccf-eui/src/styles.scss
apps/humanatlas.io/src/static/events/AUA2024/eui.html

#544 
Updated header link in the EUI

Navigation header update

---

apps/cde-ui/src/app/app.component.ts
apps/cde-ui/src/app/components/screen-size-notice/screen-size-notice.component.html
apps/cde-ui/src/app/pages/visualization/visualization.component.scss
apps/cde-ui/src/styles.scss
apps/cde-ui/src/styles/_typographies.scss
apps/cde-ui/src/styles/global/_fonts.scss
apps/cde-visualization-wc/src/styles.scss
libs/cde-visualization/src/index.html
libs/cde-visualization/src/lib/cde-visualization/cde-visualization.component.scss
libs/cde-visualization/src/lib/components/cell-types/cell-types.component.scss
libs/cde-visualization/src/lib/components/color-picker-label/color-picker-label.component.scss
libs/cde-visualization/src/lib/components/histogram/histogram.component.scss
libs/cde-visualization/src/lib/components/histogram/histogram.component.ts
libs/cde-visualization/src/lib/components/metadata/metadata.component.scss
libs/cde-visualization/src/lib/components/node-dist-visualization/node-dist-visualization.component.scss
libs/cde-visualization/src/lib/components/visualization-header/visualization-header.component.scss

#499 (excluding histogram styles)

Cde visualization app updates

---

apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.html

Updated template links on cde create visualization page ( #556 )

Change template links

---

apps/humanatlas.io/src/assets/content/pages/3d-reference-library.yaml

Per Katy, added 3D ref total. Per Andi, added text. Per Bruce, added purl URL.

Add 3D ref total, text, & purl link to 3D ref yaml

---

libs/design-system/scrolling/src/lib/scroll-overflow-fade/scroll-overflow-fade.directive.stories.ts
libs/design-system/scrolling/src/lib/scrolling.stories.ts

Showcases scrollbar variants - 8px and 12px thickness
Closes #521

feat(design-system): Add scrollbar stories

---

libs/design-system/app-logos/src/lib/app-logos.component.scss
libs/design-system/apps-card/src/lib/apps-card.component.scss
libs/design-system/button/src/lib/button-styles/button-styles.component.scss
libs/design-system/input/src/lib/input-styles/input-styles.component.scss
libs/design-system/menu/src/lib/menu-styles/menu-styles.component.scss
libs/design-system/scrolling/src/lib/scrollbar-styles/scrollbar-styles.component.scss
libs/design-system/select/src/lib/select-styles/select-styles.component.scss
libs/design-system/src/lib/apps-sidenav-demo/apps-sidenav-demo.component.scss
libs/design-system/src/lib/divider.stories.ts
libs/design-system/src/lib/font-styles.stories.ts
libs/design-system/table/src/lib/table-styles/table-styles.component.scss
libs/design-system/tooltip-card/src/lib/tooltip-card.component.scss
libs/design-system/tree/src/lib/tree-demo/tree-demo.component.html
libs/design-system/tree/src/lib/tree-styles/tree-styles.component.scss

Design system styles fixes

---

apps/cde-ui/src/assets/data/examples/index.json

fix(cde): Add new creationTimestamp metadata to examples

---

libs/design-system/info-modal/ng-package.json
libs/design-system/info-modal/src/index.ts
libs/design-system/info-modal/src/lib/info-modal.component.html
libs/design-system/info-modal/src/lib/info-modal.component.scss
libs/design-system/info-modal/src/lib/info-modal.component.stories.ts
libs/design-system/info-modal/src/lib/info-modal.component.ts
tsconfig.base.json

Create info modal component with two variants

---

apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.html
apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.ts
apps/cde-ui/src/app/pages/landing-page/landing-page.component.html
libs/cde-visualization/src/lib/cde-visualization/cde-visualization.component.html
libs/cde-visualization/src/lib/cde-visualization/cde-visualization.component.scss
libs/cde-visualization/src/lib/components/cell-types/cell-types.component.scss
libs/cde-visualization/src/lib/components/histogram/histogram.component.scss
libs/cde-visualization/src/lib/components/histogram/histogram.vl.json
libs/cde-visualization/src/lib/components/metadata/metadata.component.scss
libs/cde-visualization/src/lib/components/violin/violin.vl.json
libs/design-system/input/src/lib/input-styles/input-styles.component.scss
libs/design-system/nav-header-buttons/src/lib/nav-header-buttons.component.html
libs/design-system/table/src/lib/table-styles/table-styles.component.scss

- CDE logo link in header now points to root instead of humanatlas.io
- Required inputs on Create page disabled until data set is uploaded https://github.com/hubmapconsortium/hra-ui/issues/579#issuecomment-2450608216
- Fixed background colors on Visualization page

Cde improvements

---

apps/ccf-rui/src/app/core/store/reference-data/reference-data.state.ts

When uploading RUI registrations for editing, check the representation of against the organ list. Fixes #761

fix: :bug: fix RUI upload bug wrong sex

---

libs/design-system/nav-header/src/lib/nav-header.component.scss

#825 Display CDE sidenav properly on small screen sizes

Add max width to sidenav

---

CHANGELOG.md
apps/ccf-eui/project.json
apps/ccf-rui/project.json

Bump EUI to v4.1.0
Bump RUI to v4.1.0

Version bumps and changelog

---

apps/humanatlas.io/src/assets/content/pages/standard-operating-procedures.yaml
apps/humanatlas.io/src/assets/content/pages/vccf.yaml

minor update to VCCF.yaml
updates to standard-operating-procedures.yaml to add new SOPs and remove obsolete as per Issue: https://github.com/hubmapconsortium/hra-ui/issues/852

Hra-portal-revisions-ellen

---

README.md
apps/dashboard-ui/README.md
apps/dashboard-ui/src/app/components/header/header.component.html
apps/dashboard-ui/src/app/components/header/header.component.spec.ts
apps/humanatlas.io/src/app/shared/navigation-items.ts
apps/humanatlas.io/src/assets/content/pages/release-notes/v2.1.yaml
apps/humanatlas.io/src/assets/content/pages/release-notes/v2.2.yaml
apps/humanatlas.io/src/assets/content/pages/user-story/7.yaml
libs/design-system/nav-header-buttons/src/lib/nav-header-buttons.component.stories.ts
libs/design-system/nav-header/src/lib/nav-header.component.stories.ts

Change 'Dashboards' to 'Dashboard'

---

apps/ccf-rui/src/app/modules/metadata/modal/metadata-modal.component.ts

Fix upload during edit metadata in rui

---

apps/humanatlas.io/src/app/app-routing.module.ts
apps/humanatlas.io/src/app/components/page-data/page-data.component.html
apps/humanatlas.io/src/app/components/page-data/page-data.ts
apps/humanatlas.io/src/app/components/page-element/page-element.component.ts
apps/humanatlas.io/src/app/shared/navigation-items.ts
apps/humanatlas.io/src/app/utils/data-schema.ts
apps/humanatlas.io/src/assets/content/pages/team.yaml
apps/humanatlas.io/src/pages.schema.json

Humanatlas.io publications nav button

---

apps/humanatlas.io/src/app/app-routing.module.ts
apps/humanatlas.io/src/app/components/page-data/page-data.component.html
apps/humanatlas.io/src/app/components/page-data/page-data.ts
apps/humanatlas.io/src/app/components/page-element/page-element.component.ts
apps/humanatlas.io/src/app/shared/navigation-items.ts
apps/humanatlas.io/src/app/utils/data-schema.ts
apps/humanatlas.io/src/assets/content/pages/team.yaml
apps/humanatlas.io/src/pages.schema.json

* feat(app:humanatlas.io): Add publications nav button
* refactor(app:humanatlas.io): Improve scroll offset for anchor scrolling

Humanatlas.io publications nav button (#940)

---

apps/ccf-eui/src/app/app.component.ts
apps/ccf-eui/src/app/core/header/header.component.html
apps/ccf-eui/src/app/core/header/header.component.ts
apps/ccf-eui/src/app/core/services/theming/theming.service.ts

Header will now properly select the logo without depending on the class list order of the root element 🙄

Fix header logo selection

---

apps/ccf-rui/src/app/modules/metadata/metadata.service.ts

Clear AS tags on new registation upload

---

libs/cde-visualization/src/lib/components/node-dist-visualization/controls/node-dist-visualization-controls.component.ts
libs/design-system/button-toggle/src/lib/button-toggle-styles/button-toggle-styles.component.scss

- Fix for #976
This will be temporary until the new button toggle global styles are merged from develop

Fix button toggle selected appearance

---

libs/design-system/buttons/visual-button/src/lib/visual-button.component.html
libs/design-system/buttons/visual-button/src/lib/visual-button.component.scss
libs/design-system/buttons/visual-button/src/lib/visual-button.component.ts

Updated the mat icon to arrow_right_alt
and updated label font to Large

Updating visual button cosmetics

---

apps/humanatlas.io/src/assets/content/pages/team.yaml

Added 3 publications and edited a couple citation styles.

Publications text content update

---

apps/apps.humanatlas.io/src/app/app.config.ts
apps/apps.humanatlas.io/src/app/app.routes.ts
apps/apps.humanatlas.io/src/app/utils/navigation.ts
libs/design-system/buttons/breadcrumbs/src/lib/breadcrumbs.component.scss
libs/design-system/navigation/header/src/lib/header.component.scss
libs/design-system/navigation/header/src/lib/header.component.ts

This pull request resolves the GitHub issue: #1059.
- Add breadcrumbs configuration to each page (except landing page)
- Update header to close menus on router navigations
- Update progress bar color and add a minimum delay before the progress bar is shown

HRA - Global Improvements/Changes

---

libs/design-system/buttons/radio-button/ng-package.json
libs/design-system/buttons/radio-button/src/index.ts
libs/design-system/buttons/radio-button/src/lib/global-styles.component.scss
libs/design-system/buttons/radio-button/src/lib/global-styles.component.ts
libs/design-system/buttons/radio-button/src/lib/providers.ts
libs/design-system/buttons/radio-button/src/lib/radio-button.component.stories.ts
libs/design-system/buttons/src/lib/providers.ts

Changes cherry picked from #1071

Radio buttons with correct base branch

---

libs/design-system/buttons/button/src/lib/button.stories.ts
libs/design-system/buttons/button/src/lib/global-styles.component.scss

Initial commit for the extended FAB button

Extended FAB button

---

apps/humanatlas.io/src/app/components/toolbar/toolbar.component.html

- Lisel and Andi's HRA survey ends at noon today
- Adding my HRA website feedback survey link that is open until May 1

Update CTA bar message and route

---

libs/design-system/indicators/progress-spinner/ng-package.json
libs/design-system/indicators/progress-spinner/src/index.ts
libs/design-system/indicators/progress-spinner/src/lib/progress-spinner.component.html
libs/design-system/indicators/progress-spinner/src/lib/progress-spinner.component.scss
libs/design-system/indicators/progress-spinner/src/lib/progress-spinner.component.spec.ts
libs/design-system/indicators/progress-spinner/src/lib/progress-spinner.component.stories.ts
libs/design-system/indicators/progress-spinner/src/lib/progress-spinner.component.ts
libs/design-system/indicators/src/index.ts
libs/design-system/tooltips/rich-tooltip/src/lib/content/rich-tooltip-content.component.spec.ts

This pull request resolves the dependency sub-issue #1087.
Also fixed some tests for the rich tooltip to pass jest test coverage threshold.

Design System - Progress Spinner

---

apps/ccf-rui/src/app/shared/components/rotation-slider/slider-box/slider-box.component.html
apps/ccf-rui/src/app/shared/components/slices-input/slices-input.component.html
apps/ccf-rui/src/app/shared/components/slices-input/slices-input.module.ts

Update tooltip text in tissue block settings

---

apps/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.html
apps/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.ts
apps/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.module.ts
apps/ccf-rui/src/app/shared/components/rotation-slider/slider-box/slider-box.component.html
apps/ccf-rui/src/app/shared/components/rotation-slider/slider-box/slider-box.component.scss
apps/ccf-rui/src/app/shared/components/rotation-slider/slider-box/slider-box.component.ts
apps/ccf-rui/src/app/shared/components/rotation-slider/slider-box/slider-box.module.ts

Reimplemented rotation slider using overlay for slider-box

---

.github/workflows/build-previews.yml
package-lock.json
package.json

* update workflow to use Netlify CLI
* remove ftu filter
* add filter again and add explicit auth and site params
* remove auth and site vars
* remove extract step
* remove json flag
* add back the json
* update netlify deploy command
* add debug flag and update the directory path
* add no build flag
* add no-build flag, remove debug flag and update dir flag
* move extract step in deploy step
* update jq from .url to .deploy_url
* remove comments and print lines
* remove node js step

Cherry pick netlify ci fixes from develop

---

apps/humanatlas.io/src/app/app.routes.ts
apps/humanatlas.io/src/assets/content/ccf-ontology-page/data.yaml

Issue- #1160 
Added Common Coordinate Framework Ontology Page.

Content Pages- CCF ontology page

---

apps/humanatlas.io/src/app/app.config.ts
apps/humanatlas.io/src/app/schemas/content-page/content-page.schema.json
apps/humanatlas.io/src/app/schemas/content-page/content-page.schema.ts
libs/design-system/buttons/button/src/index.ts
libs/design-system/buttons/button/src/lib/button.component.html
libs/design-system/buttons/button/src/lib/button.component.scss
libs/design-system/buttons/button/src/lib/button.component.ts
libs/design-system/buttons/button/src/lib/types/button.definition.ts
libs/design-system/buttons/button/src/lib/types/button.schema.ts

Adds button component for use in content template

Add content template button component

---

apps/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html
apps/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.ts
libs/ccf-shared/src/lib/components/opacity-slider/opacity-slider.component.html

- Update a youtube link
- Fix rotation sliders snapping back to previous values #1206 
- Fix landmark visibility input field #1207

Rui hotfixes

---

libs/common/src/index.ts
libs/common/src/lib/assets-href/asset-url.ts
libs/common/src/lib/assets-href/tokens.ts
libs/common/src/lib/utils/url.ts
libs/design-system/buttons/text-hyperlink/src/lib/text-hyperlink.component.ts
libs/design-system/table/src/lib/table/table.component.ts

This fix is part of the [#1214](https://github.com/hubmapconsortium/hra-ui/issues/1214)

Ponyfill for URL.parse()

---

apps/apps.humanatlas.io/src/app/app.component.ts
apps/humanatlas.io/src/app/app.component.ts
apps/humanatlas.io/src/app/app.config.ts
apps/humanatlas.io/src/app/controllers/data-viewer-param-sync/data-viewer-param-sync.service.ts
libs/common/custom-scroll/ng-package.json
libs/common/custom-scroll/src/index.ts
libs/common/custom-scroll/src/lib/custom-scroll.service.ts

This PR address the issue of scroll on top when query params change on some pages.
Here is the [issue](https://github.com/hubmapconsortium/hra-ui/issues/1232)

add custom scroll service

---

apps/humanatlas.io/src/app/app.routes.ts
apps/humanatlas.io/src/assets/content/cell-distance-explorer-page/data.yaml

This pull request resolves #1238.

HumanAtlas.io - CDE Content Page

---

apps/humanatlas.io/src/app/app.routes.ts
apps/humanatlas.io/src/assets/content/cell-population-predictor-page/data.yaml

This PR resolves [issue](https://github.com/hubmapconsortium/hra-ui/issues/1278)

Add Cell population predictor

---

libs/design-system/content-templates/app-label/src/lib/app-label.component.scss

add flex-shrink and set it to 0

Update logo on resize

---

apps/humanatlas.io/src/assets/content/2d-ftu-illustrations/data.yaml
apps/humanatlas.io/src/assets/content/omap-faqs-page/data.yaml

This PR resolves the [issue](https://github.com/hubmapconsortium/hra-ui/issues/1289)

Add secondary cta on ftu page

---

apps/apps.humanatlas.io/src/app/app.component.html
apps/apps.humanatlas.io/src/app/app.component.ts
apps/apps.humanatlas.io/src/app/app.routes.ts
apps/apps.humanatlas.io/src/app/pages/us1/cell-population-predictor/cell-population-predictor.component.html
apps/apps.humanatlas.io/src/app/pages/us1/cell-population-predictor/cell-population-predictor.component.spec.ts
apps/apps.humanatlas.io/src/app/pages/us2/tissue-origin-predictor/tissue-origin-predictor.component.html
apps/apps.humanatlas.io/src/app/pages/us2/tissue-origin-predictor/tissue-origin-predictor.component.spec.ts
apps/apps.humanatlas.io/src/app/pages/us6/web-components.component.html

Adding secondary navigation for apps.humanatlas.io

Secondary navigation for apps

---

apps/ccf-eui/src/app/modules/spatial-search/spatial-search-ui/spatial-search-ui.component.html
apps/ccf-eui/src/app/modules/spatial-search/spatial-search-ui/spatial-search-ui.component.scss
apps/ccf-eui/src/app/modules/spatial-search/term-occurence-list/term-occurrence.component.scss
apps/ccf-eui/src/app/modules/spatial-search/tissue-block-list/tissue-block-list.component.scss
apps/humanatlas.io/src/assets/content/eui-page/data.yaml

EUI updates from #1309
- Spatial search: Collapse category needs to visually reduce in size
- Help route on spatial search: Route for spatial search modal needs to go to spatial search section of humanatlas.io/exploration-user-interface

Eui tweaks

---

apps/apps.humanatlas.io/src/app/app.routes.ts
apps/dashboard-ui/src/app/app.component.html
apps/dashboard-ui/src/app/app.component.ts
apps/dashboard-ui/src/app/app.routes.ts
libs/dashboard/src/lib/components/dashboard-layout/dashboard-layout.component.scss
libs/design-system/buttons/breadcrumbs/src/lib/breadcrumbs.component.html

- applied fix for absolute urls in breadcrumbs
- fix line height for dashboard page paragraphs
- update breadcrumbs for apps and dashboard apps
- added tooltips for secondary navigation buttons

HRA Dashboard UI Fixes/Improvements

---

apps/apps.humanatlas.io/src/app/pages/us1/cell-population-predictions/cell-population-predictions.component.html

- Issue linked #1325 
- fixed issue with order in us1, cell population predictions table, should be in desc

Fixed order issue in us1 table

---

apps/docs.humanatlas.io/public/assets/content/apps-overview-page/data.yaml

Refer [issue](https://github.com/hubmapconsortium/hra-ui/issues/1357)

update learn more URL for KG card

---

libs/design-system/navigation/site-navigation/src/lib/navigation-category/navigation-category.component.scss
libs/design-system/navigation/site-navigation/src/lib/navigation-item/navigation-item.component.scss

Tweak hover and selected state buttons to match Figma

Update side nav styles

---

apps/ccf-eui/src/app/app.component.scss
apps/ccf-eui/src/app/modules/filters/autocomplete-chip-form/autocomplete-chips-form.component.html
apps/ccf-eui/src/app/modules/filters/autocomplete-chip-form/autocomplete-chips-form.component.scss
apps/ccf-eui/src/app/modules/filters/autocomplete-chip-form/autocomplete-chips-form.component.ts
apps/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.scss

This pull request closes the bug issue #1374.

EUI Filter Form Autocomplete Fixes

---

apps/humanatlas.io/src/app/app.component.ts
apps/humanatlas.io/src/app/utils/route-data.ts
libs/design-system/navigation/site-navigation/src/lib/navigation-item/navigation-item.component.scss
libs/design-system/navigation/site-navigation/src/lib/site-navigation.component.ts

This pull request resolves the bug issue #1378.

Humanatlas Docs Navigation Fixes

---

apps/ftu-ui/src/app/app.component.html
apps/ftu-ui/src/app/app.component.ts
apps/ftu-ui/src/app/app.config.ts
apps/ftu-ui/src/app/ftu-components/atoms/src/lib/label-box/label-box.component.scss
apps/ftu-ui/src/app/ftu-components/atoms/src/lib/label-box/label-box.component.ts
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/medical-illustration-behavior/medical-illustration-behavior.component.html
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/medical-illustration-behavior/medical-illustration-behavior.component.ts
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/tissue-library-behavior/tissue-library-behavior.component.html
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/tissue-library-behavior/tissue-library-behavior.component.scss
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/tissue-library-behavior/tissue-library-behavior.component.ts
apps/ftu-ui/src/app/ftu-components/molecules/src/lib/tissue-tree-list/tissue-tree-list.component.html
apps/ftu-ui/src/app/ftu-components/molecules/src/lib/tissue-tree-list/tissue-tree-list.component.scss
apps/ftu-ui/src/app/ftu-components/molecules/src/lib/tissue-tree-list/tissue-tree-list.component.ts
libs/design-system/menu/src/index.ts

This PR updates the FTU navigation list component. Please refer  issue #1422

Ftu navigation list

---

apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/biomarker-details/biomarker-details.component.scss
apps/ftu-ui/src/app/ftu-components/molecules/src/lib/source-list/source-list.component.html
apps/ftu-ui/src/app/ftu-components/molecules/src/lib/source-list/source-list.component.scss
apps/ftu-ui/src/app/ftu-components/molecules/src/lib/source-list/source-list.component.spec.ts
apps/ftu-ui/src/app/ftu-components/molecules/src/lib/source-list/source-list.component.ts
libs/design-system/table/src/lib/table/table.component.html
libs/design-system/table/src/lib/table/table.component.scss
libs/design-system/table/src/lib/table/table.component.stories.ts
libs/design-system/table/src/lib/table/table.component.ts
libs/design-system/table/src/lib/types/page-table.schema.ts

Update source list

---

apps/humanatlas.io/src/assets/content/ftu-explorer-page/data.yaml

Correct preprint route to Nature DOI route

Update secondary button route to publication DOI

---

apps/ccf-eui/src/app/app.component.html
apps/ccf-eui/src/app/app.component.ts
apps/ccf-eui/src/app/core/store/data/data.state.ts
apps/ccf-eui/src/app/modules/filters/filters-content/filters-content.component.ts
libs/ccf-scene-utils/package.json
libs/ccf-shared/src/lib/services/data-source/api-endpoint.service.ts
libs/ccf-shared/src/lib/services/data-source/data-source.service.ts
libs/ccf-shared/src/lib/services/data-source/data-source.ts
package-lock.json
package.json

- Linked Issue #1418 
- updated package @hra-api/ng-client to latest
- updated UI to use new route /v1/consortium-names to populate list in filter

Updated EUI to use /v1/consortium-names in filter consortia options

---

libs/design-system/dialog/src/lib/notice/notice.component.scss

Issue linked- #1431 Dialog Box

Updated styles in dialog box

---

libs/design-system/src/lib/providers.ts
libs/design-system/styles/_theming.scss
libs/design-system/styles/overrides/_index.scss
libs/design-system/styles/overrides/_tabs.scss
libs/design-system/tabs/ng-package.json
libs/design-system/tabs/src/index.ts
libs/design-system/tabs/src/lib/tabs/providers.ts
libs/design-system/tabs/src/lib/tabs/tabs.component.stories.ts

This pull request resolves GitHub issue #919.
- Implemented style overrides inside design system library.
- Implemented custom configuration using `MAT_TABS_CONFIG` to disable `stretchTabs`.
- Implemented storybook demonstration story.

Design System - Tabs

---

apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/biomarker-details/biomarker-details.component.html
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/biomarker-details/biomarker-details.component.scss
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/biomarker-details/biomarker-details.component.ts
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/medical-illustration-behavior/medical-illustration-behavior.component.html
apps/ftu-ui/src/app/ftu-components/behavioral/src/lib/medical-illustration-behavior/medical-illustration-behavior.component.ts
apps/ftu-ui/src/app/ftu-components/organisms/src/lib/biomarker-table/biomarker-table.component.html
apps/ftu-ui/src/app/ftu-components/organisms/src/lib/biomarker-table/biomarker-table.component.scss
apps/ftu-ui/src/app/ftu-components/organisms/src/lib/biomarker-table/biomarker-table.component.spec.ts
apps/ftu-ui/src/app/ftu-components/organisms/src/lib/biomarker-table/biomarker-table.component.ts
libs/design-system/bottom-sheet/src/bottom-sheet.service.ts
libs/design-system/bottom-sheet/src/lib/bottom-sheet.component.html
libs/design-system/bottom-sheet/src/lib/bottom-sheet.component.scss
libs/design-system/bottom-sheet/src/lib/bottom-sheet.component.ts
libs/design-system/table/src/lib/table/table.component.html
libs/design-system/table/src/lib/table/table.component.stories.ts
libs/design-system/table/src/lib/table/table.component.ts

Overall improvements to the biomarker details component, custom table variant without headers for bottom sheet and other improvements

Biomarker details and table improvements

---

apps/humanatlas.io/src/assets/content/training-page/data.yaml

Update route to SOP Glossary: https://docs.google.com/document/d/1IBuPOt2mkPOOMF9vUsZk5HQ3vm9M7WjnlW-ZOMG6wSY/edit?tab=t.0#heading=h.ihfnxsruj8m7

Update SOP Glossary route

---

apps/asctb-reporter/src/app/components/home/home.component.html
apps/asctb-reporter/src/app/components/home/home.component.ts

This pull request contains files for the ASCT+B reporter landing page.

add asseturl pipe to landing page splash

---

apps/asctb-reporter/src/app/app.component.html

ASCT+B Reporter Nav Header - Fix Broken Links

---

apps/ftu-ui/src/app/app.component.html
libs/design-system/cards/profile-card/src/lib/profile-card.component.scss
libs/design-system/cards/profile-card/src/lib/profile-card.component.stories.ts

Resolves the following GH issue:
- #1502

Design System - Profile Card

---

apps/humanatlas.io/src/assets/content/standard-operating-procedures-page/data.yaml

Update incorrect DOI link to https://doi.org/10.5281/zenodo.7901004
- Closes #1569

Update SOP route with DOI

---

apps/asctb-reporter/src/app/app.component.html
apps/asctb-reporter/src/app/components/compare/compare.component.scss
apps/asctb-reporter/src/app/components/organ-table-selector/organ-table-selector.component.html
apps/asctb-reporter/src/app/components/sidenav/sidenav.component.scss
apps/asctb-reporter/src/app/modules/tree/spec/groups/bimodal.ts
apps/asctb-reporter/src/app/modules/tree/spec/groups/tree.ts
apps/asctb-reporter/src/app/modules/tree/tree.component.scss
apps/asctb-reporter/src/styles.scss

This pull request resolves the following issues:
- #1575
- #1576

ASCT+B Reporter - Fixes and Cosmetic Improvements

---

apps/ftu-ui/src/assets/links.yml
libs/state/src/lib/active-ftu/active-ftu.state.spec.ts
libs/state/src/lib/active-ftu/active-ftu.state.ts

Add correct Illustartion link to the Link registry

---

apps/cde-ui/src/app/app.routes.ts
apps/dashboard-ui/src/app/app.routes.ts
apps/humanatlas.io/src/app/app.routes.ts
apps/kg-explorer/src/app/app.routes.ts

- Ensure all redirects starts with a `/`
- Added `pathMatch: 'full'` where necessery

Fix router redirects

---

apps/ccf-eui/src/app/core/store/spatial-search-ui/spatial-search-ui.selectors.ts

Ensure dimensions are numeric in spatial search

---

apps/apps.humanatlas.io/src/app/pages/cell-population-graph/components/bar-graph/bar-graph.component.ts
apps/apps.humanatlas.io/src/app/pages/cell-population-graph/components/config-selector/config-selector.component.html
apps/apps.humanatlas.io/src/app/pages/hra-pop-visualizer/components/bar-graph/bar-graph.component.spec.ts
apps/apps.humanatlas.io/src/app/pages/hra-pop-visualizer/components/bar-graph/bar-graph.component.ts
apps/apps.humanatlas.io/src/app/pages/hra-pop-visualizer/components/config-selector/config-selector.component.html

- Improvements in apps event tracking

Analytics improvements in apps.humanatlas.io

---

apps/cde-ui/src/app/pages/create-visualization-page/create-visualization-page.component.html

This PR updates analytics in the cde-ui

Update cde-ui analytics

---

apps/ccf-rui/src/app/app.component.html
apps/ccf-rui/src/app/app.component.ts
apps/ccf-rui/src/app/app.module.ts
apps/ccf-rui/src/app/core/store/model/model.state.ts
apps/ccf-rui/src/app/core/store/registration/registration.state.spec.ts
apps/ccf-rui/src/app/core/store/scene/scene.state.ts
apps/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
apps/ccf-rui/src/app/modules/left-sidebar/left-sidebar.module.ts
apps/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html
apps/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.ts

Add axis toggles and update menus

---

apps/ftu-ui/src/app/pages/ftu-page/ftu.component.scss
libs/design-system/.storybook/preview.ts
libs/design-system/snackbar/src/lib/snackbar.component.scss
libs/design-system/table/src/lib/table/table.component.html
libs/ftu-ui-components/src/lib/atoms/src/lib/label-box/label-box.component.scss

FTU - Minor Fixes
